import os
import time
import logging
import datetime
from typing import Tuple

logger = logging.getLogger("research_engine")
os.makedirs("logs", exist_ok=True)
os.makedirs("reports", exist_ok=True)
fh = logging.FileHandler("logs/research.log", encoding="utf-8")
fh.setFormatter(logging.Formatter('%(asctime)s - %(message)s'))
logger.addHandler(fh)

def _clean_data_via_ai(topic: str, raw_text: str, style: str, layer_used: str) -> Tuple[str, str]:
    """Uses AI to either format scraped data or generate the data directly from its knowledge base."""
    provider = os.getenv("AI_PROVIDER", "gemini").lower()
    
    if layer_used == "live web research":
        prompt = (
            f"You are an expert researcher. I have scraped some raw web data about '{topic}'.\n"
            f"Your task is to write a highly professional, well-structured report using this data.\n"
            f"Style requested: {style}\n\n"
            "Rules:\n"
            "- Remove duplicate lines and promotional junk.\n"
            "- Fix grammar and improve readability.\n"
            "- Use Markdown headers (##), bullet points, and clean paragraphs.\n"
            "- Do NOT use markdown code block formatting, just output the raw text directly.\n"
            f"Raw Data (excerpt):\n{raw_text[:6000]}"
        )
    else:
        prompt = (
            f"You are an expert researcher. Your task is to write a highly professional, comprehensive report on the topic '{topic}'.\n"
            f"Style requested: {style}\n\n"
            "Rules:\n"
            "- Write an extensive, beginner-friendly guide with useful facts.\n"
            "- Use professional headers (##), bullet points, and clear paragraphs.\n"
            "- Add a summary and conclusion.\n"
            "- Do NOT use markdown code block formatting, just output the raw text directly."
        )
    
    # Layer 2: Cloud AI (Gemini)
    try:
        if provider == "gemini":
            from google import genai
            client = genai.Client()
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
            )
            final_layer = layer_used if layer_used == "live web research" else "AI knowledge mode"
            return response.text, final_layer
    except Exception as e:
        logger.warning(f"Primary AI failed for research: {e}. Falling back to Local AI.")
        
    # Layer 3: Local Offline AI (Ollama)
    try:
        import ollama
        model = os.getenv("OLLAMA_MODEL", "qwen2.5:3b")
        response = ollama.chat(model=model, messages=[
            {"role": "user", "content": prompt}
        ])
        final_layer = layer_used if layer_used == "live web research" else "offline local summary mode"
        return response['message']['content'], final_layer
    except Exception as e:
        logger.error(f"Fallback AI also failed: {e}")
        return "Error: Could not generate data via AI.", "failed"

def create_docx(topic: str, content: str, filepath: str):
    from docx import Document
    doc = Document()
    doc.add_heading(f"Research Report: {topic.title()}", 0)
    doc.add_paragraph(f"Generated by Lotus AI on {datetime.date.today()}")
    
    for line in content.split('\n'):
        line = line.strip()
        if not line:
            continue
        if line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('- ') or line.startswith('* '):
            doc.add_paragraph(line[2:], style='List Bullet')
        else:
            doc.add_paragraph(line)
    doc.save(filepath)

def create_pdf(topic: str, content: str, filepath: str):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    story.append(Paragraph(f"Research Report: {topic.title()}", styles['Title']))
    story.append(Paragraph(f"Generated by Lotus AI on {datetime.date.today()}", styles['Normal']))
    story.append(Spacer(1, 12))
    
    for line in content.split('\n'):
        line = line.strip()
        if not line:
            continue
        if line.startswith('#'):
            story.append(Paragraph(line.replace('#', '').strip(), styles['Heading2']))
        elif line.startswith('- ') or line.startswith('* '):
            story.append(Paragraph(line, styles['Bullet']))
        else:
            story.append(Paragraph(line, styles['Normal']))
        story.append(Spacer(1, 6))
        
    doc.build(story)

def create_xlsx(topic: str, content: str, filepath: str):
    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Research Data"
    
    ws.append(["Topic", topic.title()])
    ws.append(["Date", str(datetime.date.today())])
    ws.append([])
    
    for row_idx, line in enumerate(content.split('\n'), start=4):
        ws.cell(row=row_idx, column=1, value=line.strip())
        
    wb.save(filepath)

def create_txt(topic: str, content: str, filepath: str):
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"Research Report: {topic.title()}\n")
        f.write(f"Generated by Lotus AI on {datetime.date.today()}\n")
        f.write("="*50 + "\n\n")
        f.write(content)

async def perform_research(topic: str, file_type: str = "chat", style: str = "professional") -> Tuple[bool, str, str]:
    """
    Performs web search, cleans data via AI, generates requested file format.
    Returns (success, message, filepath)
    """
    start_time = time.time()
    logger.info(f"Starting research on '{topic}' (Type: {file_type})")
    
    layer_used = "live web research"
    raw_data = ""
    
    # 1. Scrape data (Layer 1)
    from windows_mcp.tools.browser import search_google
    temp_file = "temp_scrape.txt"
    try:
        search_google(topic, temp_file)
        if os.path.exists(temp_file):
            with open(temp_file, 'r', encoding='utf-8') as f:
                raw_data = f.read()
        if len(raw_data.strip()) < 50:
            raise ValueError("Web search returned insufficient data.")
    except Exception as e:
        logger.warning(f"Web scraping failed: {e}. Moving to Layer 2.")
        layer_used = "AI knowledge mode"
        
    # 2. Generate/Clean data via AI (Layer 2 & 3)
    clean_data, final_layer = _clean_data_via_ai(topic, raw_data, style, layer_used)
    
    if clean_data.startswith("Error:"):
        return False, clean_data, ""
        
    # 3. Create document
    if file_type == "chat":
        logger.info(f"Research finished in {int(time.time() - start_time)}s using {final_layer}")
        summary_intro = f"📊 *Research completed using {final_layer}.*\n\n"
        return True, summary_intro + clean_data, ""
        
    safe_topic = "".join([c if c.isalnum() else "_" for c in topic.strip()][:20])
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    filename = f"Research_{safe_topic}_{date_str}.{file_type}"
    filepath = os.path.join(os.getcwd(), "reports", filename)
    
    try:
        if file_type == "docx":
            create_docx(topic, clean_data, filepath)
        elif file_type == "pdf":
            create_pdf(topic, clean_data, filepath)
        elif file_type == "xlsx":
            create_xlsx(topic, clean_data, filepath)
        else: # txt
            create_txt(topic, clean_data, filepath)
            
        time_taken = int(time.time() - start_time)
        logger.info(f"Success | Topic: {topic} | Layer: {final_layer} | Type: {file_type} | Time: {time_taken}s")
        
        # Keep it concise for telegram
        summary = f"📊 *Research completed using {final_layer}.*\nTopic: `{topic}`\nFormat: `{file_type}`\nTime taken: `{time_taken}s`"
        return True, summary, filepath
        
    except Exception as e:
        logger.error(f"File creation failed: {e}")
        return False, f"Report created but file export failed: {e}", ""
