class AXRole:
    APPLICATION     = "AXApplication"
    WINDOW          = "AXWindow"
    BUTTON          = "AXButton"
    TEXT_FIELD      = "AXTextField"
    TEXT_AREA       = "AXTextArea"
    STATIC_TEXT     = "AXStaticText"
    CHECK_BOX       = "AXCheckBox"
    RADIO_BUTTON    = "AXRadioButton"
    COMBO_BOX       = "AXComboBox"
    POP_UP_BUTTON   = "AXPopUpButton"
    MENU            = "AXMenu"
    MENU_ITEM       = "AXMenuItem"
    MENU_BAR        = "AXMenuBar"
    MENU_BAR_ITEM   = "AXMenuBarItem"
    LIST            = "AXList"
    CELL            = "AXCell"
    TABLE           = "AXTable"
    ROW             = "AXRow"
    COLUMN          = "AXColumn"
    SCROLL_AREA     = "AXScrollArea"
    SCROLL_BAR      = "AXScrollBar"
    SLIDER          = "AXSlider"
    TAB_GROUP       = "AXTabGroup"
    TOOL_BAR        = "AXToolbar"
    GROUP           = "AXGroup"
    SPLIT_GROUP     = "AXSplitGroup"
    SPLITTER        = "AXSplitter"
    IMAGE           = "AXImage"
    LINK            = "AXLink"
    WEB_AREA        = "AXWebArea"
    GENERIC         = "AXGenericElement"
    UNKNOWN         = "AXUnknown"
    OUTLINE         = "AXOutline"
    DISCLOSURE      = "AXDisclosureTriangle"
    STEPPER         = "AXIncrementor"
    SEARCH_FIELD    = "AXSearchField"
    PROGRESS        = "AXProgressIndicator"
    TOOLBAR_BUTTON  = "AXToolbarButton"


class AXAttr:
    ROLE                = "AXRole"
    SUBROLE             = "AXSubrole"
    TITLE               = "AXTitle"
    VALUE               = "AXValue"
    DESCRIPTION         = "AXDescription"
    HELP                = "AXHelp"
    PLACEHOLDER         = "AXPlaceholderValue"
    CHILDREN            = "AXChildren"
    PARENT              = "AXParent"
    WINDOWS             = "AXWindows"
    FOCUSED_WINDOW      = "AXFocusedWindow"
    FOCUSED_ELEMENT     = "AXFocusedUIElement"
    POSITION            = "AXPosition"
    SIZE                = "AXSize"
    ENABLED             = "AXEnabled"
    FOCUSED             = "AXFocused"
    SELECTED            = "AXSelected"
    HIDDEN              = "AXHidden"
    MINIMIZED           = "AXMinimized"
    MAIN                = "AXMain"
    SELECTED_TEXT       = "AXSelectedText"
    NUMBER_OF_CHARS     = "AXNumberOfCharacters"
    ROWS                = "AXRows"
    COLUMNS             = "AXColumns"
    VERTICAL_SCROLL_BAR = "AXVerticalScrollBar"
    CONTENTS            = "AXContents"


class AXAction:
    PRESS       = "AXPress"
    PICK        = "AXPick"
    CONFIRM     = "AXConfirm"
    CANCEL      = "AXCancel"
    SHOW_MENU   = "AXShowMenu"
    DECREMENT   = "AXDecrement"
    INCREMENT   = "AXIncrement"
    RAISE       = "AXRaise"


class AXNotification:
    FOCUSED_UI_ELEMENT_CHANGED = "AXFocusedUIElementChanged"
    APPLICATION_ACTIVATED      = "AXApplicationActivated"
    APPLICATION_DEACTIVATED    = "AXApplicationDeactivated"
    WINDOW_CREATED             = "AXWindowCreated"
    VALUE_CHANGED              = "AXValueChanged"
